Load libraries/packages

In [14]:
import pandas as pd 
import numpy as np
import sklearn
import matplotlib.pyplot as plt 
from sklearn import linear_model
from sklearn.model_selection import train_test_split


Load housing data 

In [15]:
df = pd.read_csv('train.csv', index_col='Id')
df

MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
Id                                                                      
1             60       RL         65.0     8450   Pave   NaN      Reg   
2             20       RL         80.0     9600   Pave   NaN      Reg   
3             60       RL         68.0    11250   Pave   NaN      IR1   
4             70       RL         60.0     9550   Pave   NaN      IR1   
5             60       RL         84.0    14260   Pave   NaN      IR1   
...          ...      ...          ...      ...    ...   ...      ...   
1456          60       RL         62.0     7917   Pave   NaN      Reg   
1457          20       RL         85.0    13175   Pave   NaN      Reg   
1458          70       RL         66.0     9042   Pave   NaN      Reg   
1459          20       RL         68.0     9717   Pave   NaN      Reg   
1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities LotConfig  ... PoolArea PoolQC  Fence MiscFeature  \
Id                                    ...                                      
1            Lvl    AllPub    Inside  ...        0    NaN    NaN         NaN   
2            Lvl    AllPub       FR2  ...        0    NaN    NaN         NaN   
3            Lvl    AllPub    Inside  ...        0    NaN    NaN         NaN   
4            Lvl    AllPub    Corner  ...        0    NaN    NaN         NaN   
5            Lvl    AllPub       FR2  ...        0    NaN    NaN         NaN   
...          ...       ...       ...  ...      ...    ...    ...         ...   
1456         Lvl    AllPub    Inside  ...        0    NaN    NaN         NaN   
1457         Lvl    AllPub    Inside  ...        0    NaN  MnPrv         NaN   
1458         Lvl    AllPub    Inside  ...        0    NaN  GdPrv        Shed   
1459         Lvl    AllPub    Inside  ...        0    NaN    NaN         NaN   
1460         Lvl    AllPub    Inside  ...        0    NaN    NaN         NaN   

     MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
Id                                                               
1          0      2    2008        WD         Normal     208500  
2          0      5    2007        WD         Normal     181500  
3          0      9    2008        WD         Normal     223500  
4          0      2    2006        WD        Abnorml     140000  
5          0     12    2008        WD         Normal     250000  
...      ...    ...     ...       ...            ...        ...  
1456       0      8    2007        WD         Normal     175000  
1457       0      2    2010        WD         Normal     210000  
1458    2500      5    2010        WD         Normal     266500  
1459       0      4    2010        WD         Normal     142125  
1460       0      6    2008        WD         Normal     147500  

[1460 rows x 80 columns]

Use for loop to drop columns with NaN

In [16]:

columns = []
for col in df:
  if df[col].isnull().any()==True:
    # print(col)
    columns.append(col)
print(columns)
for col in columns:
  df.drop([col], axis=1, inplace=True)
df

['LotFrontage', 'Alley', 'MasVnrType', 'MasVnrArea', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Electrical', 'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageQual', 'GarageCond', 'PoolQC', 'Fence', 'MiscFeature']


MSSubClass MSZoning  LotArea Street LotShape LandContour Utilities  \
Id                                                                         
1             60       RL     8450   Pave      Reg         Lvl    AllPub   
2             20       RL     9600   Pave      Reg         Lvl    AllPub   
3             60       RL    11250   Pave      IR1         Lvl    AllPub   
4             70       RL     9550   Pave      IR1         Lvl    AllPub   
5             60       RL    14260   Pave      IR1         Lvl    AllPub   
...          ...      ...      ...    ...      ...         ...       ...   
1456          60       RL     7917   Pave      Reg         Lvl    AllPub   
1457          20       RL    13175   Pave      Reg         Lvl    AllPub   
1458          70       RL     9042   Pave      Reg         Lvl    AllPub   
1459          20       RL     9717   Pave      Reg         Lvl    AllPub   
1460          20       RL     9937   Pave      Reg         Lvl    AllPub   

     LotConfig LandSlope Neighborhood  ... EnclosedPorch 3SsnPorch  \
Id                                     ...                           
1       Inside       Gtl      CollgCr  ...             0         0   
2          FR2       Gtl      Veenker  ...             0         0   
3       Inside       Gtl      CollgCr  ...             0         0   
4       Corner       Gtl      Crawfor  ...           272         0   
5          FR2       Gtl      NoRidge  ...             0         0   
...        ...       ...          ...  ...           ...       ...   
1456    Inside       Gtl      Gilbert  ...             0         0   
1457    Inside       Gtl       NWAmes  ...             0         0   
1458    Inside       Gtl      Crawfor  ...             0         0   
1459    Inside       Gtl        NAmes  ...           112         0   
1460    Inside       Gtl      Edwards  ...             0         0   

     ScreenPorch PoolArea  MiscVal  MoSold  YrSold  SaleType SaleCondition  \
Id                                                                           
1              0        0        0       2    2008        WD        Normal   
2              0        0        0       5    2007        WD        Normal   
3              0        0        0       9    2008        WD        Normal   
4              0        0        0       2    2006        WD       Abnorml   
5              0        0        0      12    2008        WD        Normal   
...          ...      ...      ...     ...     ...       ...           ...   
1456           0        0        0       8    2007        WD        Normal   
1457           0        0        0       2    2010        WD        Normal   
1458           0        0     2500       5    2010        WD        Normal   
1459           0        0        0       4    2010        WD        Normal   
1460           0        0        0       6    2008        WD        Normal   

     SalePrice  
Id              
1       208500  
2       181500  
3       223500  
4       140000  
5       250000  
...        ...  
1456    175000  
1457    210000  
1458    266500  
1459    142125  
1460    147500  

[1460 rows x 61 columns]

Getting necessary columns from the data 


In [17]:
new_df = df[['Neighborhood', 'YrSold', 'SalePrice']]
new_df

Neighborhood  YrSold  SalePrice
Id                                  
1         CollgCr    2008     208500
2         Veenker    2007     181500
3         CollgCr    2008     223500
4         Crawfor    2006     140000
5         NoRidge    2008     250000
...           ...     ...        ...
1456      Gilbert    2007     175000
1457       NWAmes    2010     210000
1458      Crawfor    2010     266500
1459        NAmes    2010     142125
1460      Edwards    2008     147500

[1460 rows x 3 columns]

Get dummy variables 

In [18]:
dummies =pd.get_dummies(new_df.Neighborhood)

merge datasets 

In [19]:
merged = pd.concat([new_df, dummies], axis='columns')
merged.shape 

(1460, 28)

Dropping columns 

In [20]:
df2 = merged.drop(columns = ['Neighborhood', 'Veenker'])
df2 

YrSold  SalePrice  Blmngtn  Blueste  BrDale  BrkSide  ClearCr  CollgCr  \
Id                                                                             
1       2008     208500        0        0       0        0        0        1   
2       2007     181500        0        0       0        0        0        0   
3       2008     223500        0        0       0        0        0        1   
4       2006     140000        0        0       0        0        0        0   
5       2008     250000        0        0       0        0        0        0   
...      ...        ...      ...      ...     ...      ...      ...      ...   
1456    2007     175000        0        0       0        0        0        0   
1457    2010     210000        0        0       0        0        0        0   
1458    2010     266500        0        0       0        0        0        0   
1459    2010     142125        0        0       0        0        0        0   
1460    2008     147500        0        0       0        0        0        0   

      Crawfor  Edwards  ...  NWAmes  NoRidge  NridgHt  OldTown  SWISU  Sawyer  \
Id                      ...                                                     
1           0        0  ...       0        0        0        0      0       0   
2           0        0  ...       0        0        0        0      0       0   
3           0        0  ...       0        0        0        0      0       0   
4           1        0  ...       0        0        0        0      0       0   
5           0        0  ...       0        1        0        0      0       0   
...       ...      ...  ...     ...      ...      ...      ...    ...     ...   
1456        0        0  ...       0        0        0        0      0       0   
1457        0        0  ...       1        0        0        0      0       0   
1458        1        0  ...       0        0        0        0      0       0   
1459        0        0  ...       0        0        0        0      0       0   
1460        0        1  ...       0        0        0        0      0       0   

      SawyerW  Somerst  StoneBr  Timber  
Id                                       
1           0        0        0       0  
2           0        0        0       0  
3           0        0        0       0  
4           0        0        0       0  
5           0        0        0       0  
...       ...      ...      ...     ...  
1456        0        0        0       0  
1457        0        0        0       0  
1458        0        0        0       0  
1459        0        0        0       0  
1460        0        0        0       0  

[1460 rows x 26 columns]

Import Linear Model 

In [21]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [22]:
X = df2.drop(columns = ['SalePrice'])
X.columns

Index(['YrSold', 'Blmngtn', 'Blueste', 'BrDale', 'BrkSide', 'ClearCr',
       'CollgCr', 'Crawfor', 'Edwards', 'Gilbert', 'IDOTRR', 'MeadowV',
       'Mitchel', 'NAmes', 'NPkVill', 'NWAmes', 'NoRidge', 'NridgHt',
       'OldTown', 'SWISU', 'Sawyer', 'SawyerW', 'Somerst', 'StoneBr',
       'Timber'],
      dtype='object')

In [23]:
y = df2[['SalePrice']]

Fit Model

In [24]:
model.fit(X.values,y)

LinearRegression()

In [25]:
model.predict([[2008,0 , 0, 0, 0, 0, 1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]])


array([[197805.86785007]])

In [26]:
model.score(X.values,y)

0.5457627420816678

One hot Encoder 

In [27]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
enc = OneHotEncoder(handle_unknown='ignore')
le = LabelEncoder()

In [28]:
df3 = new_df
df3 

Neighborhood  YrSold  SalePrice
Id                                  
1         CollgCr    2008     208500
2         Veenker    2007     181500
3         CollgCr    2008     223500
4         Crawfor    2006     140000
5         NoRidge    2008     250000
...           ...     ...        ...
1456      Gilbert    2007     175000
1457       NWAmes    2010     210000
1458      Crawfor    2010     266500
1459        NAmes    2010     142125
1460      Edwards    2008     147500

[1460 rows x 3 columns]

In [29]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
X = df3[['Neighborhood', 'YrSold']].values
X

array([['CollgCr', 2008],
       ['Veenker', 2007],
       ['CollgCr', 2008],
       ...,
       ['Crawfor', 2010],
       ['NAmes', 2010],
       ['Edwards', 2008]], dtype=object)

In [30]:
y = df3[['SalePrice']].values
y

array([[208500],
       [181500],
       [223500],
       ...,
       [266500],
       [142125],
       [147500]], dtype=int64)

In [40]:
X = ohe.fit_transform(X)


TypeError: A sparse matrix was passed, but dense data is required. Use X.toarray() to convert to a dense numpy array.

In [39]:
model.fit(X,y)

LinearRegression()

In [33]:
model.predict([[0,0 , 0, 0, 0, 0, 1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]])

array([[210056.77285033]])

In [34]:
model.score(X,y)

0.5459127321884549